// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgqprhhyzjgwoaxyfysy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNncXByaGh5empnd29heHlmeXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjUxMDYsImV4cCI6MjA2MDkwMTEwNn0.eJBb2dfNZ8LE5XyLxaFg94gBAGhH71Ug8GlDa-sAuWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);